org: heverson
app: sls-terra-nova
service: sls-terra-nova
frameworkVersion: '2 || 3'

custom:
  webpack:
    packager: 'yarn'
    includeModules:
      packagePath: './package.json' 
      
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  getCheckout:
    handler: src/handler.getCheckout
    events:
      - httpApi:
          path: /checkout
          method: post
